start-at-login = true

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

[workspace-to-monitor-force-assignment]

"1" = 'main'
"2" = 'main'
"3" = 'secondary'

[[on-window-detected]]
if.app-name-regex-substring = 'KeePassXC'
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-name-regex-substring = 'ChatGPT'
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-name-regex-substring = 'Safari'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'Mail'
run = 'move-node-to-workspace 4'

[gaps]

inner.horizontal = 8
inner.vertical =   8
outer.left =       8
outer.bottom =     8
outer.top =        8
outer.right =      8

[mode.main.binding]

cmd-enter   = 'exec-and-forget open -n -a WezTerm'
ctrl-alt-s = 'exec-and-forget open -n -a Safari'
ctrl-alt-m = 'exec-and-forget open -n -a Mail'
ctrl-alt-c = 'exec-and-forget open -n -a ChatGPT'
ctrl-alt-p = 'exec-and-forget open -n -a KeePassXC'
ctrl-alt-o = 'exec-and-forget open -n -a Obsidian'
ctrl-alt-v = 'exec-and-forget open -n -a "Visual Studio Code"'

alt-h = 'focus --boundaries-action wrap-around-the-workspace left'
alt-j = 'focus --boundaries-action wrap-around-the-workspace down'
alt-k = 'focus --boundaries-action wrap-around-the-workspace up'
alt-l = 'focus --boundaries-action wrap-around-the-workspace right'

alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

alt-ctrl-h = 'join-with left'
alt-ctrl-j = 'join-with down'
alt-ctrl-k = 'join-with up'
alt-ctrl-l = 'join-with right'

alt-s = 'layout v_accordion'
alt-w = 'layout h_accordion'
alt-e = 'layout tiles horizontal vertical'

alt-shift-space = 'layout floating tiling'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-tab       = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

alt-f       = 'fullscreen'
alt-shift-f = 'macos-native-fullscreen'

alt-r = 'mode resize'

alt-shift-q = 'close'

alt-shift-c = 'reload-config'

[mode.resize.binding]

h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'

enter = 'mode main'
esc   = 'mode main'
